repos:
-   repo: https://github.com/codespell-project/codespell
    rev: v1.15.0
    hooks:
    -   id: codespell
        args: [--ignore-words=.codespell-whitelist,--exclude-file=examples/cn0549/ml_fan_example.ipynb]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
    -   id: isort
      #-   repo: https://github.com/pre-commit/mirrors-mypy
      #    rev: v0.720
      #    hooks:
      #    -   id: mypy
      #        args: [--no-strict-optional, --ignore-missing-imports]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: check-docstring-first
    -   id: flake8
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.3.0
    hooks:
    -   id: blacken-docs
-   repo: https://github.com/pycqa/pylint
    rev: pylint-2.7.1
    hooks:
    -   id: pylint
